spring:
  application:
    name: kafka-streams-error-handler
  kafka:
    streams:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:mock://testUrl}
        default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}

stream:
  string:
    inputTopic: A
    outputTopic: B
  avro:
    input: NestedIn
    output: NestedOut

