spring:
  application:
    name: kafka-streams-error-handler
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}

stream:
  string:
    inputTopic: A
    outputTopic: B
  avro:
    input: NestedIn
    output: NestedOut

